### ISSUE TITLE
i want contribute some code to FederatedScope，which branch to commit?

### ISSUE THREAD

**Issue by MiKKiYang** [alibaba/FederatedScope#104]
@joneswong @glendon84 @Osier-Yi @xieyxclack

**Comment by xieyxclack** [comment]
We greatly appreciate any contribution to FederatedScope! You can maintain your own repository that forked from FederatedScope, and then create cross-repository pull requests into alibaba/FederatedScope:master :)

Please refer to https://federatedscope.io/docs/contributor/ for more details.

Thanks again!

**Comment by xieyxclack** [comment]
Hope that helps! This thread is closed and let us know if you have more questions.
