### ISSUE TITLE
Support different configs for different client

### ISSUE THREAD

**Issue by wanghh7** [alibaba/FederatedScope#113]
https://github.com/alibaba/FederatedScope/blob/b4914e68d40ce102fde676e92478e6181ace520c/federatedscope/core/fed_runner.py#L224-L225

Here the model uses the global configuration instead of the client configuration.

**Comment by joneswong** [comment]
I think both contest branch and master branch have this issue. @DavdGao could you fix them?

**Comment by DavdGao** [comment]
Thanks, this issue is tracked in #115
