### ISSUE TITLE
A keyword indicates the task type

### ISSUE THREAD

**Issue by wanghh7** [alibaba/FederatedScope#114]
Is it possible to add a keyword, such as cfg.federate.task_type, to indicate the task type of each client? It is useful in calculating the loss function because y_true should be long and float respectively for classification and regression tasks.

**Comment by rayrayraykk** [comment]
You could use this [key](https://github.com/alibaba/FederatedScope/blob/b413df1ee08709a95f6b84585c40b9c8dffdc787/federatedscope/core/configs/cfg_model.py#L14), to indicate the task like `cfg.model.task = 'NodeClassification'` or `'NodeRegression'` and fix trainer and monitor accordingly.

**Comment by joneswong** [comment]
It seems that it is necessary to have a list of all these args since they are not explained in docstrings (cannot be found in api ref)
