### ISSUE TITLE
One quick question

### ISSUE THREAD

**Issue by dragon5100** [alibaba/FederatedScope#121]

**Comment by xieyxclack** [comment]
Thanks for your interest! Please feel free to let us know if you have any questions or suggestions :)

**Comment by dragon5100** [comment]
How do I resolve WARNING: cannot import name 'Server' from 'federatedscope.core.worker.server' (C:\Users\DRAGON\Desktop\FederatedScope-master\federatedscope\core\worker\server.py) in `federatedscope.contrib.trainer`, some modules are not available.

**Comment by dragon5100** [comment]
2022-05-31 11:20:27,602 (trainer:583) ERROR: current flop count implementation is for general trainer case: 1) ctx.data_batch = [x, y]; and2) the ctx.model takes only x as input.Please check the forward format or implement your own flop_count function

**Comment by xieyxclack** [comment]
> 2022-05-31 11:20:27,602 (trainer:583) ERROR: current flop count implementation is for general trainer case: 1) ctx.data_batch = [x, y]; and2) the ctx.model takes only x as input.Please check the forward format or implement your own flop_count function

Please provide more detail about your experiments, such as the dataset, model, and trainer type :)

**Comment by dragon5100** [comment]
cfg.trainer.type = 'general'，cfg.data.type = 'FEMNIST'，cfg.model.type = 'ConvNet2'

**Comment by xieyxclack** [comment]
> cfg.trainer.type = 'general'，cfg.data.type = 'FEMNIST'，cfg.model.type = 'ConvNet2'

So do you run the example provided in the tutorial, as:
```
python federatedscope/main.py --cfg federatedscope/example_configs/femnist.yaml
```
Or task some customization? Since the provided example can be run successfully in the playground, I need more information to help you debug :)

**Comment by xieyxclack** [comment]
This thread is closed, and let us know if you have more questions.  Welcome to join our Slack channel or DingDing group for discussion :)

Thanks again for your interest!
