### ISSUE TITLE
Extremely slow in instantiating FL runner

### ISSUE THREAD

**Issue by joneswong** [alibaba/FederatedScope#139]
When we use subthread to execute FL (what we do in autotune module now), @rayrayraykk  observe that it is extremely slow to instantiate an FL runner (data loader may be the bottleneck).

**Comment by joneswong** [comment]
This pr is just a workaround. We need to locate what causes this issue in the future.

**Comment by rayrayraykk** [comment]
This happens when too frequent requests are sent to the thread (`is_set()`) causing the `Dataloader` to build slowly:
We can add a `time.sleep(1)` to avoid this.
```python
  for i, config in enumerate(configs):
      available_worker = 0
      while not flags[available_worker].is_set():
          available_worker = (available_worker + 1) % len(threads)
          time.sleep(1)
```
