### ISSUE TITLE
Guidance for running the example in FederatedScope/scripts/

### ISSUE THREAD

**Issue by xieyxclack** [alibaba/FederatedScope#143]
Although FederatedScope provides different kinds of scripts in FederatedScope/scripts/,  it is a little hard for users to understand these scripts without some guidance, such as which example is running for a certain script and how to use these scripts for customized tasks. 

Maybe some detailed guidance on the scripts should be provided for users. Thanks :)

**Comment by rayrayraykk** [comment]
I have moved gfl-related scripts to `gfl`, and provided a `README` in this [PR](https://github.com/alibaba/FederatedScope/pull/279). Some config keys change for some reason, in other words, lots of scripts are outdated and unavailable. I suggest a hotfix to fix this problem.

**Comment by xieyxclack** [comment]
We can add hyperlinks and docs in `scripts` as #305

**Comment by xieyxclack** [comment]
The documents have been provided in `FederatedScope/scripts/`, many thanks for your contributions!
