### ISSUE TITLE
是否支持m1？

### ISSUE THREAD

**Issue by zhangpeng528** [alibaba/FederatedScope#163]
当前在apple m1上docker build，发现cuda无法兼容，然后miniconda版本也需要是aarch版本。

**Comment by xieyxclack** [comment]
Thanks for your interest! The suggested PyTorch version (1.8 or 1.10) cannot support running on M1 with GPUs since the GPU part of M1 is not based on nvidia CUDA. Maybe you can run FederatedScope with CPUs on M1 or run with other devices :)

**Comment by zhangpeng528** [comment]
FederatedScope设计理念很不错，我非常想尝试。
在cpu上也可以尝试下，是否有指引示例提供出来？谢谢
另外是否有规划有可视化界面？当前因为未成功跑起来，文档中也没未见类似相关文档。

**Comment by xieyxclack** [comment]
You can set up `use_gpu: False` in `federatedscope/example_configs/femnist.yaml` (or other config file) and run the example on CPUs like:
```
python federatedscope/main.py --cfg federatedscope/example_configs/femnist.yaml
```
And we are working on supporting visualization with WandB and thanks a lot for your suggestion! If you have questions during your journey of Federated Learning, you can join our slack channel or DingDing group and have some discussion.

Thanks again for your interest!

**Comment by rayrayraykk** [comment]
You are more than welcome to use FS with M1 chips, we have added the guidance for M1 users in #192 .
Thanks again for your interest!
