### ISSUE TITLE
Cannot set different data related parameters for different clients.

### ISSUE THREAD

**Issue by DavdGao** [alibaba/FederatedScope#186]
As the title says, since the dataset is loaded before both `fedrunner.run()` and the setup of clients, the `config_per_client.yaml` doesn't work for the dataset, such as different batch size.

**Comment by DavdGao** [comment]
- Also, when FS finish the initialization of the global config, all unused configs are removed. However, if someone want to run a certain algorithm for some clients by the `--cfg_client xxx.yaml`, it will report `attribute error` since all related parameters within the config have been removed and the default value of `cfg.${METHOD_NAME}.__new_allowed__` is `False`.
- Another bug is that when combine the global_cfg with the client specific configs, the global_cfg will call the assert function s again. Considering all unused parameters have been removed, some assert function will report attribute errors.

**Comment by xieyxclack** [comment]
We need a discussion about how to resolve this issue. @joneswong @yxdyc @rayrayraykk
