### ISSUE TITLE
A bug for wandb monitor.

### ISSUE THREAD

**Issue by DavdGao** [alibaba/FederatedScope#191]
In this [line](https://github.com/alibaba/FederatedScope/blob/master/federatedscope/core/worker/server.py#L318), `self._cfg.wandb.use` should be written in the font of `online_track`, otherwise, it reports attribute error.

**Comment by rayrayraykk** [comment]
This has been fixed in #188 .

**Comment by rayrayraykk** [comment]
This has been fixed in #188 .
