### ISSUE TITLE
Cannot run gfl with link prediction dataset RecSys. 

### ISSUE THREAD

**Issue by Starry-Hu** [alibaba/FederatedScope#193]
For link-level recommendation system dataset, e.g. RecSys(name='ciao'), **there is None for processed data.x**, which is necessary for model building. So we cannot run it successfully. Please check it.
Located at `federatedscope/gfl/model/model_builder.py`
<img width="642" alt="image" src="https://user-images.githubusercontent.com/38689546/175939114-fa223320-889e-403a-a754-c646067d292f.png">

Besides, there is a 404 URL bug for downloading dataset for RecSys if self.FL is True, which is caused by modified self.name. 
Located at `federatedscope/gfl/dataset/recsys.py`
<img width="965" alt="image" src="https://user-images.githubusercontent.com/38689546/175938634-822776e2-d3af-498e-93ac-78a47b1d7794.png">
You can keep the same self.name for downloading, and modify the raw_dir() and processed_dir() method to distinguish the FL dataset and client dataset.

**Comment by rayrayraykk** [comment]
Thanks for your suggestions, we will fix this as soon as possible.

**Comment by Starry-Hu** [comment]
I solved this `None data.x` problem by adding pre_transform for these link-level dataset. 
It is shown in `federatedscope/gfl/baseline/fedavg_gcn_minibatch_on_kg.yaml` with config `pre_transform: ['Constant', {'value':1.0, 'cat':False}]`

But I am confused about the training process for link-prediction dataset. 
1. Referring to your `LinkFullBatchTrainer` implementation in `federatedscope/gfl/trainer/linktrainer.py`, why we need `input_edge_index` in forward for train data and valid data?
2. Referring to your `LinkFullBatchTrainer` implementation in `federatedscope/gfl/trainer/linktrainer.py`, I want to implement the training with the whole edge_index data rather than batch. So I discard `index_loader` and `perm`. However, what I get `pred` is tensor([]). I am not familiar with the link-prediction task. Could you provide a simple demo for me to refer?

Thanks!

**Comment by Starry-Hu** [comment]
> I solved this `None data.x` problem by adding pre_transform for these link-level dataset. It is shown in `federatedscope/gfl/baseline/fedavg_gcn_minibatch_on_kg.yaml` with config `pre_transform: ['Constant', {'value':1.0, 'cat':False}]`
> 
> But I am confused about the training process for link-prediction dataset.
> 
> 1. Referring to your `LinkFullBatchTrainer` implementation in `federatedscope/gfl/trainer/linktrainer.py`, why we need `input_edge_index` in forward for train data and valid data?
> 2. Referring to your `LinkFullBatchTrainer` implementation in `federatedscope/gfl/trainer/linktrainer.py`, I want to implement the training with the whole edge_index data rather than batch. So I discard `index_loader` and `perm`. However, what I get `pred` is tensor([]). I am not familiar with the link-prediction task. Could you provide a simple demo for me to refer?
> 
> Thanks!

I solved it! There is a mistake of out_channel assignment in my code.
