### ISSUE TITLE
to improve the versatility when import ?

### ISSUE THREAD

**Issue by mmwan101010** [alibaba/FederatedScope#199]
maybe u cloud add code as below in 
FederatedScope-0.1.0\federatedscope\main.py line 8
to  improve the versatility when import?
==============================================
basic_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(basic_dir)

**Comment by rayrayraykk** [comment]
Thanks for your suggestion, but set [DEV_MODE](https://github.com/alibaba/FederatedScope/blob/b996fc7947d66fb5ddf7022de1c0abd3560ca2fe/federatedscope/main.py#L4) to True works the same, right?
