### ISSUE TITLE
Support run FL courses when the server doesn't have data

### ISSUE THREAD

**Issue by xieyxclack** [alibaba/FederatedScope#208]
In the current version, we need the `server_data` for building a model and getting a trainer, but in some cases, the server doesn't have the data or only has test data. 
Furthermore, does the server really need a trainer?  I find that the server's trainer is only used for evaluation.

**Comment by DavdGao** [comment]
In some way, the `aggregator` is the training routine within the server, but it cannot support the test routine.

**Comment by rayrayraykk** [comment]
The data indicate some information like input dim, h/w in CNN. If no data is provided,  the users should set the specific number for each args of the model.
