### ISSUE TITLE
Redundancy in the log files

### ISSUE THREAD

**Issue by rayrayraykk** [alibaba/FederatedScope#22]
A Fedavg on 5% of FEMNIST trail will produce a 500 kb log each round:
with 80% eval logs like `2022-04-13 16:33:24,901 (client:264) INFO: Client #1: (Evaluation (test set) at Round #26) test_loss is 79.352451`. And 10% is server results and 10% is train informations. 

If the round is 500, 1000, or much larger, the log files will take up too much space with a lot of redundancy. @yxdyc

**Comment by yxdyc** [comment]
The output logging files are currently redundant, leading to disk space wastage and difficulties to find key results from the logging files. We may save the ``raw_metrics'' and ``training_metrics'' in other two log files with compact format.

**Comment by rayrayraykk** [comment]
> The output logging files are currently redundant, leading to disk space wastage and difficulties to find key results from the logging files. We may save the `raw_metrics` and `training_metrics` in other two log files with compact format.

And we should delete the logs below, which have already been reported on the server-side.
https://github.com/alibaba/FederatedScope/blob/24deff53055d309c3ef02e58cb7a544036b4d5ec/federatedscope/core/worker/client.py#L260

**Comment by rayrayraykk** [comment]
Another issue is the eval results of the global evaluation mode are empty, we should fix this.

**Comment by yxdyc** [comment]
> > The output logging files are currently redundant, leading to disk space wastage and difficulties to find key results from the logging files. We may save the `raw_metrics` and `training_metrics` in other two log files with compact format.
> 
> And we should delete the logs below, which have already been reported on the server-side.
> 
> https://github.com/alibaba/FederatedScope/blob/24deff53055d309c3ef02e58cb7a544036b4d5ec/federatedscope/core/worker/client.py#L260

We still need this log when we are in distributed mode. Do you agree we mask these logs only in the ``simulation'' mode? @rayrayraykk

**Comment by rayrayraykk** [comment]
> > > The output logging files are currently redundant, leading to disk space wastage and difficulties to find key results from the logging files. We may save the `raw_metrics` and `training_metrics` in other two log files with compact format.
> > 
> > 
> > And we should delete the logs below, which have already been reported on the server-side.
> > https://github.com/alibaba/FederatedScope/blob/24deff53055d309c3ef02e58cb7a544036b4d5ec/federatedscope/core/worker/client.py#L260
> 
> We still need this log when we are in distributed mode. Do you agree we mask these logs only in the ``simulation'' mode? @rayrayraykk

Agree.

**Comment by yxdyc** [comment]
Solved in #29
