### ISSUE TITLE
Monitoring improvement: visualization support 

### ISSUE THREAD

**Issue by yxdyc** [alibaba/FederatedScope#24]
The monitoring can be improved in terms of the visualization support.

To use visualization tools such as wandb or tensorboard, we currently parse the log file after the results saved. We need to support results logging in real time rather the two-step style. Besides, the parsing process should be automatic for better usability.

We can discuss other requirements for visualization here @rayrayraykk

**Comment by rayrayraykk** [comment]
* I'm not sure this feature will meet the demand of someone who attempts to get a learning curve with error bars (different seeds).
* We can group the same metric (with different splits) in one figure.

**Comment by yxdyc** [comment]
Resolved in #90. If necessary, we can re-open this issue again.
