### ISSUE TITLE
CIKMCUP fedavg baseline doesn't save predictions

### ISSUE THREAD

**Issue by ahn1340** [alibaba/FederatedScope#249]
Hello,

first of all, thank you for creating a valuable library and organizing this competition!

I tried to run the fedavg baseline, as stated in the cikmcup documentation, without any modification. I see that the code runs correctly, but contrary to what is written in the documentation, it saves neither the models nor the submission file. Afterwards, I created prediction folder manually and added prediction_path: prediction under eval of in federatedscope/gfl/baseline/fedavg_gin_minibatch_on_cikmcup.yaml, but it still does not save anything.

Could you please let me know how to create the models and the submission file properly, and maybe refer me to the part of the code where the saving happens? Thank you very much.

**Comment by DavdGao** [comment]
@ahn1340 Thanks for your interests!
- FS supports to save the prediction results at the end of the training, the code related to saving is in https://github.com/alibaba/FederatedScope/blob/cikm22competition/federatedscope/gfl/trainer/graphtrainer.py#L87 , and the function `save_prediction` is called by https://github.com/alibaba/FederatedScope/blob/cikm22competition/federatedscope/core/worker/client.py#L454
- Currently the prediction directory defaults to `prediction/prediction.csv`. After merging #247 into the cikm22competition branch,  user can specify the saving directory by `config.eval.prediction_path`. 
- The log of saving prediction results follows [image](https://img.alicdn.com/imgextra/i1/O1CN01eb3zR21QUsyjdXAM6_!!6000000001980-2-tps-4920-404.png)

**Comment by ahn1340** [comment]
Thank you for the detailed response. After merging the latest changes, it now saves the prediction properly. I have another question: does the code not save models to disk? I assumed that the final performance would be evaluated on the checkpoint that had the best validation performance, but I don't see any intermediate models being saved. Is there such a feature to allow users to save the models?

**Comment by ahn1340** [comment]
I'll close the issue btw, since the original issue has been resolved.
