### ISSUE TITLE
Bug when registering custom trainer

### ISSUE THREAD

**Issue by ahn1340** [alibaba/FederatedScope#275]
When users register a custom trainer with a file name of, e.g., MyTrainer.py in federatedscope/contrib/trainer/, a ValueError from call_link_level_trainer() in gfl/trainer/linktrainer.py, line 210, is raised.

This is because in core/auxiliaries/trainer_builder.py, line 97, the code iterates through the list of custom registered trainers, and call_link_level_trainer() in gfl/trainer/linktrainer.py is called, which raises ValueError because trainer_type of the custom trainer does not match. Therefore, trainer_builder is not able to find the custom trainer that users registered.

To reproduce this, one can simlpy register a custom model that calls line 97 in trainer_builder.py.

To fix this, the call function can be modified to return None if trainer_type does not match, then the iteration in trainer_builder.py, line 97 will work properly.

I made a  [PR](https://github.com/alibaba/FederatedScope/pull/274) that fixes the problem. The same problem exists in nodetrainer.py, so I modified both files. This bug exists in the master branch as well as the cikm22competition branch, which may forbid the participants to register their trainer, so it should be fixed there too. #274

**Comment by xieyxclack** [comment]
Thanks a lot for your comments and pr:) Please @rayrayraykk give the review and have a discussion if necessary
