### ISSUE TITLE
Link Prediction任务中，Server端评估指标：client_best_individual有误

### ISSUE THREAD

**Issue by YoungOGtiger** [alibaba/FederatedScope#327]
client_best_individual应该是选取表现最好的client的评估参数，但是我发现，test_acc这个指标反而选取了表现最差（最低）的client的test_acc，与此同时，除了test_acc这个指标外，其余指标均选取了表现最好client的评估结果。
换句话说，client_best_individual：最好client的loss、最好client的test_total、......、最差client的test_acc、......
我觉得这里有点小问题。

**Comment by yxdyc** [comment]
Thanks for pointing this out, may I ask which script you are using? We'll reproduce it and fix it as soon as possible

**Comment by YoungOGtiger** [comment]
![image](https://user-images.githubusercontent.com/41769278/184636097-e1ff0fc9-e12d-4063-b296-c7fc026f1230.png)

**Comment by YoungOGtiger** [comment]
> Thanks for pointing this out, may I ask which script you are using? We'll reproduce it and fix it as soon as possible

好的，我刚刚上传了yaml文件截图，有一些基础的配置

**Comment by rayrayraykk** [comment]
Hi there, I have double check this issue, and I am sure it was not a bug.
As you can see in the eval logs, the `client_best_individual` has the lowest loss, which is the default key (`round_wise_update_key`==`val_avg_loss`) to pick from all clients. Unfortunately, however, it does not have the highest acc.

**Comment by YoungOGtiger** [comment]
> Hi there, I have double check this issue, and I am sure it was not a bug. As you can see in the eval logs, the `client_best_individual` has the lowest loss, which is the default key (`round_wise_update_key`==`val_avg_loss`) to pick from all clients. Unfortunately, however, it does not have the highest acc.

OK,thanks!!!
