### ISSUE TITLE
Proper assign credits to GraphGym library

### ISSUE THREAD

**Issue by JiaxuanYou** [alibaba/FederatedScope#332]
Hi team, thanks for the great work! I'm excited to learn about Federated Learning.

I'm the author of GraphGym library: https://github.com/snap-stanford/GraphGym

I discover that the structure of the codebase resembles my GraphGym library, and certain code blocks are duplicated (`contrib`, capability for registering new modules, config system etc.). Please properly add GraphGym LICENSE to the LICENSE file of this project. Please point to the GraphGym code base to recognize my efforts in the README.md.

Looking forward to get connected and collaborate in the future!

My email: youjiaxuan@gmail.com

**Comment by joneswong** [comment]
Hi jiaxuan, thanks for your kind reminder. In this pr #333 we added the copyright of GraphGym. We will also cite your paper in our FS paper if this registration mechanism is mentioned in the paper.

BTW, I learned a lot from your package as well as your other works about NAS and GNN. We are glad to have cooperation with you on federated graph learning.
