### ISSUE TITLE
ValueError: Trainer graphmaml_trainer is not provided

### ISSUE THREAD

**Issue by czkyx** [alibaba/FederatedScope#356]
ValueError: Trainer graphmaml_trainer is not provided.

**Comment by DavdGao** [comment]
Thanks for your interest. 
- The trainer `graphmaml_trainer` is used as a baseline for the benchmark `B-FHTL`, and you can run the baselines in branch `B-FHTL`. 
- As for `graphmaml_trainer`, you can find it in https://github.com/alibaba/FederatedScope/blob/feature/B-FHTL/federatedscope/gfl/trainer/mamltrainer.py

**Comment by czkyx** [comment]
Thanks a lot!!!!
