### ISSUE TITLE
Running a distributed example across four containers fails

### ISSUE THREAD

**Issue by young-chao** [alibaba/FederatedScope#359]
# 四个容器上分别准备了数据
python scripts/distributed_scripts/gen_data.py

# 服务端容器运行
python federatedscope/main.py --cfg scripts/distributed_scripts/distributed_configs/distributed_server.yaml distribute.data_file toy_data/server_data distribute.server_host 172.17.0.8 distribute.server_port 50051

# 客户端1运行
python federatedscope/main.py --cfg scripts/distributed_scripts/distributed_configs/distributed_client_1.yaml distribute.data_file toy_data/client_1_data distribute.server_host 172.17.0.8 distribute.server_port 50051 distribute.client_host 172.17.0.9 distribute.client_port 50052
# 客户端2运行
python federatedscope/main.py --cfg scripts/distributed_scripts/distributed_configs/distributed_client_2.yaml distribute.data_file toy_data/client_2_data distribute.server_host 172.17.0.8 distribute.server_port 50051 distribute.client_host 172.17.0.10 distribute.client_port 50053
# 客户端3运行
python federatedscope/main.py --cfg scripts/distributed_scripts/distributed_configs/distributed_client_3.yaml distribute.data_file toy_data/client_3_data distribute.server_host 172.17.0.8 distribute.server_port 50051 distribute.client_host 172.17.0.11 distribute.client_port 50054

终端输出始终停在如下状态：
# 服务端
2022-09-02 11:53:52,076 (server:185)INFO: Server: Listen to 172.17.0.8:50051...
2022-09-02 11:53:52,076 (fed_runner:348)INFO: Server has been set up ...
# 客户端1
2022-09-02 11:51:55,487 (client:124)INFO: Client: Listen to 172.17.0.9:50052...
2022-09-02 11:51:55,487 (fed_runner:401)INFO: Client (address 172.17.0.9:50052) has been set up ...
# 客户端2
2022-09-02 11:53:59,381 (client:124)INFO: Client: Listen to 172.17.0.1:50053...
2022-09-02 11:53:59,381 (fed_runner:401)INFO: Client (address 172.17.0.1:50053) has been set up ...
# 客户端3
2022-09-02 11:53:59,381 (client:124)INFO: Client: Listen to 172.17.0.1:50053...
2022-09-02 11:53:59,381 (fed_runner:401)INFO: Client (address 172.17.0.1:50053) has been set up ... 

很困惑，这个例子是只能单机上跑吗，四个容器中网络是通的，但是没有反应

**Comment by xieyxclack** [comment]
Thanks for your interest! The provided example in [link](https://github.com/alibaba/FederatedScope/tree/master/scripts#distribute-mode) can be executed across multiple containers or multiple devices.

From the provided logs, it seems that the server and clients have not communicated with each other (i.e., the server hasn't received the 'join_in' messages, or the clients haven't received the 'assigned_id'). 
Maybe you can check:
- The logs from client#2 and client#3 are mismatched with the provided command: `172.17.0.1` in logs, but `172.17.0.11` in command. You might need to clear the redundant jobs that are started by previous trials, which might occupy the ports.
- Make sure that the containers are connected with each other. In a successful practice, we add `--net="host"` when starting the containers and use the (public) IP addresses of the host.


Hope this help :)

**Comment by young-chao** [comment]
你好，你的邮件已收到，谢谢！

**Comment by young-chao** [comment]
> Thanks for your interest! The provided example in [link](https://github.com/alibaba/FederatedScope/tree/master/scripts#distribute-mode) can be executed across multiple containers or multiple devices.
> 
> From the provided logs, it seems that the server and clients have not communicated with each other (i.e., the server hasn't received the 'join_in' messages, or the clients haven't received the 'assigned_id'). Maybe you can check:
> 
> * The logs from client#2 and client#3 are mismatched with the provided command: `172.17.0.1` in logs, but `172.17.0.11` in command. You might need to clear the redundant jobs that are started by previous trials, which might occupy the ports.
> * Make sure that the containers are connected with each other. In a successful practice, we add `--net="host"` when starting the containers and use the (public) IP addresses of the host.
> 
> Hope this help :)

Thanks for your reply, I will follow your reply to check my ip related issues.I hope it can be solved。

**Comment by young-chao** [comment]
I have a question about how to clear the redundant jobs that are started by previous trials。

**Comment by young-chao** [comment]
My problem is solved, thanks for your reply, you can close this issue.

**Comment by xieyxclack** [comment]
Thanks again for your interest!
