### ISSUE TITLE
Installiation error

### ISSUE THREAD

**Issue by SakuraXiaMF** [alibaba/FederatedScope#363]
error: protobuf 3.19.4 is installed but protobuf<5.0dev,>=4.21.3 is required by {'grpcio-tools'}

**Comment by xieyxclack** [comment]
You can try to install `grpcio-tools=1.48.0` and `grpcio=1.48.0`

**Comment by rayrayraykk** [comment]
> Thank you for your reply. It worked. But I ran into another error. When I follow https://federatedscope.io/docs/graph/. "Start with a custom function", I meet a error "ValueError: Data my_cora not found." My data is my_cora, and my model is gnn_mygcn , but it doesn'r work.

We have made a response in #367 .
