### ISSUE TITLE
There may be a bug in the function of "__track_and_check_best"  of  "core/monitors/early_stopper.py" file

### ISSUE THREAD

**Issue by zza234s** [alibaba/FederatedScope#373]
The result of executing the code in the red box is _add(eval_score, delta) <new_result_, instead of the expected _add(eval_score, delta) >new_result_
![image](https://user-images.githubusercontent.com/52850465/189661687-60e88068-7a59-455e-8d85-531cb8932024.png)

Because of the assignment statement on line 46
![image](https://user-images.githubusercontent.com/52850465/189662074-fb68f30e-b883-41b1-b349-0c55d5d0acad.png)

**Comment by rayrayraykk** [comment]
Hello, thanks for pointing out this bug, we've fixed it in #374.
