### ISSUE TITLE
There seems to be an error with the calculation of the rmse metric

### ISSUE THREAD

**Issue by THU-syh** [alibaba/FederatedScope#376]
**an error about the calculation of rmse **
There seems to be an error with the calculation of the rmse metric, in the Line 188 of federatedscope/core/monitors/metric_calculator.py.

The original code is as follows
<img width="756" alt="image" src="https://user-images.githubusercontent.com/37439814/191003045-cd2142ee-6849-4b73-8f2c-1ca03cd49134.png">

It seems that Line 188 should be modified as follows
<img width="861" alt="image" src="https://user-images.githubusercontent.com/37439814/191003335-5cc2fcd8-2b73-432b-815d-fe39d02b83ea.png">

**Comment by xieyxclack** [comment]
Thank you for pointing out this issue! This thread is closed since we have fixed it in #378
