### ISSUE TITLE
OSError: /lib64/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by rayrayraykk** [alibaba/FederatedScope#382]
**Describe the bug**
When using the Application Version, an error might occur.

```bash
OSError: /lib64/libm.so.6: version `GLIBC_2.27' not found
```

**Comment by rayrayraykk** [comment]
It is caused by `torch-spline-conv`.

Just uninstall it by:
```bash
pip uninstall torch-spline-conv
```

**Comment by xieyxclack** [comment]
Thank you @rayrayraykk ! We hope this issue can help users who meet the same error.
