### ISSUE TITLE
Accessing trained server and client models after training is done

### ISSUE THREAD

**Issue by zyzhang1130** [alibaba/FederatedScope#393]
In the quick_start notebook, after running Fed_runner.run(), what it is proper way to get access to the trained server and client models? For example, how should I view the trained model parameters or save the model?

**Comment by rayrayraykk** [comment]
Hi there, you could use `federate.save_to` to save the model to your disk, which is picked via the evaluation round.
Optional, you can get the model param via `Fed_runner .server.trainer.get_model_para()` for the current model param.
Please refer to [here](https://github.com/alibaba/FederatedScope/tree/master/federatedscope/core/configs) for complete configuration instructions.

**Comment by zyzhang1130** [comment]
Thank you so much!
