### ISSUE TITLE
Problem with the installation

### ISSUE THREAD

**Issue by 41206703** [alibaba/FederatedScope#416]
Download error on https://pypi.org/simple/: [Errno 104] Connection reset by peer -- Some packages may not be found!
No local packages or working download links found for protobuf==3.19.4
error: Could not find suitable distribution for Requirement.parse('protobuf==3.19.4')

I follow the tutorials from https://federatedscope.io/docs/installation/, but I am faced with this problem when execute "python setup.py install" How can I deal with it? Thanks a lot.

**Comment by rayrayraykk** [comment]
Hi, do you try to update your pip or change source of pip?
Please try the following command:
```bash
pip install -e . -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
```

**Comment by 41206703** [comment]
> 

This makes for me! It seems like the source used is going wrong. And thank you for such a great work!
