### ISSUE TITLE
There may be an error in the monitor's update_best_result function.

### ISSUE THREAD

**Issue by THU-syh** [alibaba/FederatedScope#441]
### **Describe the bug**
There may be a bug in the monitor's update_best_result function.
**_File: federatedscope/core/monitors/monitor.py Lines: L652-L681_**
![image](https://user-images.githubusercontent.com/37439814/203908210-bb078125-2070-4581-ab5a-a0b47e30b7fc.png)
**Expected Result**
This function expects to update different keys round-wise, which means if find a better round_wise_update_key, update others at the same time. 

**TestCase 1**
Assuming that **_valid_acc_** is the round_wise_update_key, and it does not increase in a certain round, but the **_test_acc_** increases in this round than the best round. **The update_best_this_round should be False in this round.** However, there will have that _**update_best_this_round=True**_ when looping to the key **_test_acc_**. This error will cause all keys behind _**test_acc**_ to be updated.

**TestCase 2**
Assuming that **_valid_loss_** is the round_wise_update_key, and the results_type is in ["client_best_individual", "unseen_client_best_individual"]. If the **_valid_loss_** decreases in this round, then we have that **_update_best_this_round=True_**.  However, when looping to the key **_acc_**, we will jump into _**L661:cur_result = min(cur_result)**_. The correct code should be " cur_result = max(cur_result)".

**My code**
I tried to fix this code as below:
```
# the first key must be the round_wise_update_key,
# update_best_this_round should be set while evaluating the first key,
# so we can check whether update_best_this_round firstly

cur_result = new_results[sorted_keys[0]]
if self.the_larger_the_better:
    # The larger the better
    if results_type in [
            "client_best_individual",
            "unseen_client_best_individual"
    ]:
        cur_result = max(cur_result)
    if  key not in best_result or cur_result > best_result[key]:
        best_result[key] = cur_result
        update_best_this_round = True
else:
    # The smaller the better
    if results_type in [
            "client_best_individual",
            "unseen_client_best_individual"
    ]:
        cur_result = min(cur_result)
    if key not in best_result or cur_result < best_result[key]:
        best_result[key] = cur_result
        update_best_this_round = True

# update other metrics only if update_best_this_round is True
if update_best_this_round:
    for key in sorted_keys[1:]:
        cur_result = new_results[key]
        if results_type in [
                "client_best_individual",
                "unseen_client_best_individual"
        ]:
            # Obtain the whether the larger the better
            for mode in ['train', 'val', 'test']:
                if mode in key:
                    _key = key.split(f'{mode}_')[1]
                    if self.metric_calculator.eval_metric[_key][1]:
                        cur_result = max(cur_result)
                    else:
                        cur_result = min(cur_result)
        best_result[key] = cur_result
```

**Comment by xieyxclack** [comment]
This thread is closed since we have fixed the issue in #442 , thanks again for your contribution!
