### ISSUE TITLE
Standardize weight initialization across mulitple FL instances

### ISSUE THREAD

**Issue by zyzhang1130** [alibaba/FederatedScope#447]
Hi, I would like to ask how does FederatedScope ensure all client models are initialized with the same initial weights? The reason I want to know this is that I want to set the weight initialization in such a way that the FL training across multiple instances (i.e., 
```
Fed_runner = FedRunner(data=data,
                       server_class=get_server_cls(cfg),
                       client_class=get_client_cls(cfg),
                       config=cfg.clone())
Fed_runner.run()
```
occurs multiple times with possibly different configurations and data)

all share the same initial weights for the client models.

Thanks.

**Comment by xieyxclack** [comment]
Thank you for your interest!
You can set up the random seed (`cfg.seed`) to control the model initialization. And the server will broadcast the model parameters to clients at each training round for synchronizing the weights for the client models

**Comment by zyzhang1130** [comment]
thanks for the clarificaiton
