### ISSUE TITLE
Would 

### ISSUE THREAD

**Issue by zyzhang1130** [alibaba/FederatedScope#459]
Hi, I encountered the following unsupported operator warning during vanilla Fedavg training with convnet2 model and femnist data:
```
WARNING:fvcore.nn.jit_analysis:Unsupported operator aten::add_ encountered 2 time(s)
WARNING:fvcore.nn.jit_analysis:Unsupported operator aten::max_pool2d encountered 2 time(s)
WARNING:fvcore.nn.jit_analysis:Unsupported operator aten::add_ encountered 2 time(s)
```

I'm not sure what would be its impact on the model performance.

**Comment by xieyxclack** [comment]
These warnings are caused by fvcore package, which is used to calculate the FLOPS and has no impact on the model performance. You can set `cfg.eval.count_flops=False` to disable such operations.

**Comment by zyzhang1130** [comment]
> fvcore

Noted with thanks.

**Comment by zyzhang1130** [comment]
> These warnings are caused by fvcore package, which is used to calculate the FLOPS and has no impact on the model performance. You can set `cfg.eval.count_flops=False` to disable such operations.
Noted with thanks.
