### ISSUE TITLE
Cannot run fl training on Femnist in distribute mode

### ISSUE THREAD

**Issue by DavdGao** [alibaba/FederatedScope#483]
Please check the code in [`federatedscope/core/auxiliaries/model_builder.py`](https://github.com/alibaba/FederatedScope/blob/master/federatedscope/core/auxiliaries/model_builder.py#L65).

When running femnist in distributed mode, the server will load `data_representative` in  [`federatedscope/core/auxiliaries/model_builder.py`](https://github.com/alibaba/FederatedScope/blob/master/federatedscope/core/auxiliaries/model_builder.py#L65) as 
```
{'train': <torch.utils.data.dataloader.DataLoader object at 0x7f3a10d7b950>, 'test': <torch.utils.data.dataloader.DataLoader object at 0x7f3a10d68dd0>, 'val': <torch.utils.data.dataloader.DataLoader object at 0x7f3a10d87810>}
```
and no input_shape will be returned.

**Comment by xieyxclack** [comment]
You might need to specify `distribute.data_idx` to indicate which part of the data is owned by the server/client, or the whole femnist dataset would be returned.

An example is provided in https://github.com/alibaba/FederatedScope/blob/master/scripts/distributed_scripts/run_distributed_conv_femnist.sh
