### ISSUE TITLE
Message asked for local pretraining is missing the "content" para when train a graph model in distributed mode?

### ISSUE THREAD

**Issue by SXxtyz** [alibaba/FederatedScope#488]
If no "content" para, there will raise ValueError('The data type {} has not been supported.'.format(type(value))) in Message.create_by_type() function.

**Comment by xieyxclack** [comment]
Thanks a lot for your interest! This issue is caused by that NoneType is not supported by grpc proto, you can change None to a string (such as 'None') as a workaround.
