### ISSUE TITLE
Inappropriate way of assigning values to Client data in toy and vfl synthetic dataset

### ISSUE THREAD

**Issue by rayrayraykk** [alibaba/FederatedScope#502]
When applying feature transformation in `ClientData`, we must use `deepcopy`. Otherwise, the data in server and client will be inconsistent (in server, x = f(x), but in client, x=f(f(x))).
And I've fixed this in https://github.com/alibaba/FederatedScope/pull/486/commits/ae896cd5740dc0b34f03bc637a724edf3f3be77e, please help me to double-check if there are the same issues on other datasets, thanks! @xieyxclack

**Comment by xieyxclack** [comment]
Thank you very much for pointing out and fixing this issue!
