### ISSUE TITLE
Failed to get the results when using WandB in vFL

### ISSUE THREAD

**Issue by rayrayraykk** [alibaba/FederatedScope#505]
When using WandB to monitor vFL, an Error might occur:

```bash
Expecting property name enclosed in double quotes: line 1 column 135 (char 134)
```

The bug is caused by `json.loads(s=line)` in https://github.com/alibaba/FederatedScope/blob/86d7dc36841268508dc3569decbe5652ee33b714/federatedscope/core/auxiliaries/logging.py#L216

The line is 
```python
'{xxxx, "feature_importance": {1: [0, 1, 0, 0, 1, 2, 0], 2: [1, 0, 0, 0, 0]}}'
```
which cannot be loaded by `json`, we should replace the number in dict key with str type:
```python
'{xxxx, "feature_importance": {"1": [0, 1, 0, 0, 1, 2, 0], "2": [1, 0, 0, 0, 0]}}'
```

@qbc2016 , could you fix this?

**Comment by qbc2016** [comment]
Please see #506
