### ISSUE TITLE
How to assign The Server's IP in distributied_server.yaml

### ISSUE THREAD

**Issue by Qwtdgh** [alibaba/FederatedScope#532]
I use Four servers to distribute: one server, three clients
If my server's IP = 1.2.3.4
I want make it as a server for other three clients
I make distribute.server_ host=1.2.3.4, but it has an ERROR as follow:
Failed to bind to address 1.2.3.4:50051; set GRPC_VERBOSITY=debug environment variable to see detailed error message

After,I try 127.0.0.1 and 0.0.0.0,  thougth it can run, but the server can't connect to clients' server  

If I run distribute system in the same server, all IP are assigned as 127.0.0.1, the distribute system can run successfully

Can you help me? Thanks

**Comment by xieyxclack** [comment]
Hi, you can check the configurations as the following suggestions:
- For WAN IP: Please check the authority of the ports;
- For LAN IP: Please check whether the ports have been occupied (by previous trials);
- One suggested configuration for LAN: You can try to use 127.0.0.1/0.0.0.0 to start the grpc listening serve (please refer to [here](https://github.com/alibaba/FederatedScope/blob/master/federatedscope/core/communication.py#L64)), and specify the IP addresses in configurations (the yaml files) to be LAN IPs (1.2.3.4).


Thanks for your interest! Hope this helps :)
