### ISSUE TITLE
How do I set the Intranet and extranet ip addresses

### ISSUE THREAD

**Issue by relinda2019** [alibaba/FederatedScope#534]
For example, there are three nodes A, B, and C. A(client 1) has Intranet ip a1 and extranet ip a2, B(client 2) has Intranet ip b1 and extranet ip b2, and C(Server) has Intranet ip c1 and extranet ip c2.
How do I configure the distribute attribute in a yml file

**Comment by xieyxclack** [comment]
Hi, you can configure like:
- For server C, set `distribute.server_host=c1` and `distribute.server_port=port_c`;
- For client A/B, set `distribute.server_host=c1`, `distribute.server_port=port_c`, `distribute.client_host=a1/b1`, `distribute.client_port=port_a/port_b`.
- An example is provided in https://github.com/alibaba/FederatedScope/tree/master/scripts#distribute-mode

Hop this helps! Thanks for your interest

**Comment by relinda2019** [comment]
What if C and B can only be accessed through the external network c2 and b2? However, the program codes are deployed to Intranet ip addresses c1 and b1

**Comment by xieyxclack** [comment]
In such a case, you should provide b2/c2 for the network connecting
