### ISSUE TITLE
how can i run a vertical-xgboost trainer in distribute mode

### ISSUE THREAD

**Issue by chunhuapeng** [alibaba/FederatedScope#551]
the question is same as the tile, and  more, how can i specify my own train/test data for server/client without splitting the specified data?
can you give a runnable demo to me? my email is pcheworld@163.com
thanks a lots

**Comment by xieyxclack** [comment]
Thanks for your interest! 
- An example of running vFL-xgb in distributed mode is provided in `scripts/distributed_scripts/run_distributed_xgb.sh`.
- If you want to load data from isolated files, you need to change the configurations (i.e., yaml files) as:
   - Set `data.type = file`
   - Specify the path to your data file: `data.file_path: PATH/TO/DATA`
   - If some of the participants (such as the server) have no data, set `data.type= ''` 
   
 Hope this will help :)
