### ISSUE TITLE
Unsupported operator aten::max_pool2d encountered 2 time(s)

### ISSUE THREAD

**Issue by Hairful** [alibaba/FederatedScope#579]
I followed all the instructions on https://federatedscope.io/docs/examples/. But when I ran the sample code `python federatedscope/main.py --cfg scripts/example_configs/femnist.yaml`, this error happens, and the process is killed.
And there is no evaluation in the end. 
![](https://user-images.githubusercontent.com/96092093/233540775-2b39e442-eeac-4118-aa8f-b0200b594f86.png)

**Comment by Hairful** [comment]
By running `sudo apt autoremove`, this is solved.

**Comment by Xingyu-Romantic** [comment]
sorry，I running `sudo apt autoremove` , but it still exist

**Comment by yimhe** [comment]
Me too, I running  sudo apt autoremove, it not work.

**Comment by rayrayraykk** [comment]
> Me too, I running sudo apt autoremove, it not work.

Hello, this is a warning raised by flopscount, and it actually won't affect the FL results (you can ignore it).

**Comment by yimhe** [comment]
> > 我也是，我运行 sudo apt autoremove，它不起作用。
> 
> 您好，这是 flopscount 提出的警告，实际上不会影响 FL 结果（您可以忽略它）。

thank you

**Comment by BagelOrb** [comment]
> Hello, this is a warning raised by flopscount, and it actually won't affect the FL results (you can ignore it).

Ah yes! Now I remember. I implemented the same with flopscount and it was only then that I started getting the warnings Like " Unsupported operator aten::add_ encountered x time(s)" 

Thanks
