### ISSUE TITLE
Docs rendering error

### ISSUE THREAD

**Issue by hacker-jerry** [alibaba/FederatedScope#59]
https://federatedscope.io/docs/algozoo/#additional-functions-for-fedprox-algorithm

Here⬆️The article format seems to be a bit messed up.

<img width="807" alt="image" src="https://user-images.githubusercontent.com/57279550/166882790-a572f937-c72e-4afd-bd9f-71bebf4ea6b8.png">

**Comment by joneswong** [comment]
This thread is closed, as we have fixed this rendering issue. Thanks again!
