### ISSUE TITLE
Did scope  support vertical federated learning and is there an example

### ISSUE THREAD

**Issue by kaiwang0112006** [alibaba/FederatedScope#70]
I went throught the example of scope and didn't find a vertical federated learning example. Did flower support vertical federated learning and is there an example?

**Comment by xieyxclack** [comment]
Thanks for your interest :)
The example of vertical federated learning is provided in federatedscope/vertical_fl , and you can refer to [tutorial](https://federatedscope.io/docs/cross-silo/) for more details about this example.
