### ISSUE TITLE
  batch_or_epoch and epoch will not chage as specify value in .yaml

### ISSUE THREAD

**Issue by SpeeeedLee** [alibaba/FederatedScope#720]
I have encountered a small issue that the "train" settings are always :
batch_or_epoch : "epoch",
local_update_steps: 1
no matter how I change those values in my .yaml file.

Thank you

**Comment by qbc2016** [comment]
Hello, could you please provide your running command and the contents of your YAML file?

**Comment by SpeeeedLee** [comment]
Thanks for the reply.
It turns out its just a small detail that i didn't notice, the problem is fixed now, thank you!
