### ISSUE TITLE
I can't run the script which named "backdoor_badnet_fedavg_convnet2_on_femnist.yaml"

### ISSUE THREAD

**Issue by tntstation** [alibaba/FederatedScope#723]
Hello! I know fs from your paper "Revisiting Personalized Federated Learning: Robustness Against Backdoor Attacks".And I am studying fs in order to set up an experiment related to backdoor attacks using fs. However, I found that I cannot find relevant documentation, and the sample scripts in the code cannot be executed. Is this functionality in place, or is there an issue with my configuration environment?
Other scripts like "femnist.yaml" and "CRA_fedavg_convnet2_on_femnist.yaml" can run normally.
![屏幕截图 2023-11-23 215209](https://github.com/alibaba/FederatedScope/assets/97088494/10789535-6b11-4eb4-90ba-c9899c3458b0)

**Comment by rayrayraykk** [comment]
Looks like a key error in yaml:
Could you please change:
```yaml
federate:
    local_update_step: xxx
```
to
```yaml
train:
  local_update_steps: xxx
```
and try again?

Some keys are changed or moved due to code organization reasons. Please let me know if you meet other issues when using FS.

**Comment by tntstation** [comment]
I have modified the .yaml file according to your advice, but it seems there is more than one error in the file.
![image](https://github.com/alibaba/FederatedScope/assets/97088494/67f2d96d-3a55-4320-acd9-069de1632f7e)
![image](https://github.com/alibaba/FederatedScope/assets/97088494/1f839f47-4347-45b3-88d8-43fabe744be4)

**Comment by tntstation** [comment]
"batch_or_epoch: epoch" is what I modified based on femnist.yaml, but I'm not sure where the dataset should belong.

**Comment by rayrayraykk** [comment]
Looks like there are more changes should be made. You can refer to https://github.com/alibaba/FederatedScope/blob/master/federatedscope/core/configs/README.md 

I am not sure if the master branch is good to run with this yaml file. @Osier-Yi, can you fix this yaml file to the latest version?

**Comment by tntstation** [comment]
I checked the file you provided, but I still did not find which category "dataset" belongs to, and I also found that there were no categories of "optimizer" and "trainer" in the file，however these two are present in the.yaml file.is it the fault of the file you provided or the fault of the.yaml file?

**Comment by tntstation** [comment]
I checked the file you provided, but I still did not find which category "dataset" belongs to, and I also found that there were no categories of "optimizer" and "trainer" in the file，however these two are present in the.yaml file.is it the fault of the file you provided or the fault of the.yaml file?
![image](https://github.com/alibaba/FederatedScope/assets/97088494/2b4a8fae-f2cd-4d87-aad3-e62c85312d5e)
![image](https://github.com/alibaba/FederatedScope/assets/97088494/40f79162-3ec9-4a8b-b18c-3dbec494417b)

**Comment by Osier-Yi** [comment]
Hello! Thank you for your interest in our paper. I just want to verify which branch you are currently on. If you are in the master branch, could you please switch to the branch named "backdoor-bench"? The related scripts to conduct the backdoor attacks are under "scripts/backdoor_scripts/attack_config".

**Comment by Osier-Yi** [comment]
We apologize for any confusion caused by the documentation being located only in the master branch（ https://github.com/alibaba/FederatedScope/blob/master/benchmark/Backdoor-bench/README.md ）. We appreciate you bringing this to our attention and will work to rectify the issue as soon as possible. Thank you for your patience and understanding.

**Comment by tntstation** [comment]
Hello! I am currently using the master branch. I've checked the files you provided, but I have some concerns. As stated in the files, FS is an 'open-sourced library that updates frequently,' and I'm worried whether the existing official documentation is still valid for Backdoor-bench after many updates. If I intend to use custom datasets like MNIST, can the current official documentation serve as a reference?

**Comment by tntstation** [comment]
sorry,the errors that exist in the master branch seem to also exist in the Backdoor bench。
![image](https://github.com/alibaba/FederatedScope/assets/97088494/e7537291-e1d3-4aa2-b23b-e20316d6073b)
![image](https://github.com/alibaba/FederatedScope/assets/97088494/bc496658-8fe0-4c14-bdc2-bb67fa0c22b6)

**Comment by tntstation** [comment]
I have checked all the. yaml files in the "backdoor_scripts \ attack_config" directory and I am sure that they all have the same issue. @Osier-Yi @rayrayraykk 
![image](https://github.com/alibaba/FederatedScope/assets/97088494/b79c0040-4916-4aff-bfcc-f464ae52bfe2)
![image](https://github.com/alibaba/FederatedScope/assets/97088494/9513c11d-2fcb-412c-94af-d6968b6021d5)
![image](https://github.com/alibaba/FederatedScope/assets/97088494/4410614f-c4d3-446c-a3c7-75128752f86e)

**Comment by rayrayraykk** [comment]
> I have checked all the. yaml files in the "backdoor_scripts \ attack_config" directory and I am sure that they all have the same issue. @Osier-Yi @rayrayraykk ![image](https://private-user-images.githubusercontent.com/97088494/286559476-b79c0040-4916-4aff-bfcc-f464ae52bfe2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjA1NjksIm5iZiI6MTcwMTI2MDI2OSwicGF0aCI6Ii85NzA4ODQ5NC8yODY1NTk0NzYtYjc5YzAwNDAtNDkxNi00YWZmLWJmY2MtZjQ2NGFlNTJiZmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEyMTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYzgyYzdmNDlkYzAxMzdjNTBmMmU2NDIyODU5NjNlYWFmODE0YTgyN2U4YzE5MWZlZmYzYmJkOGIyOWY5MDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M6Gt5g_GIBTRLDqAyHCMac4erMExzjv8VIbeu_p8p-Q) ![image](https://private-user-images.githubusercontent.com/97088494/286559717-9513c11d-2fcb-412c-94af-d6968b6021d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjA1NjksIm5iZiI6MTcwMTI2MDI2OSwicGF0aCI6Ii85NzA4ODQ5NC8yODY1NTk3MTctOTUxM2MxMWQtMmZjYi00MTJjLTk0YWYtZDY5NjhiNjAyMWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEyMTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzNTk5ZDI4MzlkM2QzOGI2ODE2MTIxM2YxYjdjNGI5OTk5MDQ2YWY5MmE0MzIyNDY2YmIxY2I1NThlZWU1NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1uO1lYmrFEAi5UI8-jJQHCacU33vGejJyxSzQBCcYXo) ![image](https://private-user-images.githubusercontent.com/97088494/286559885-4410614f-c4d3-446c-a3c7-75128752f86e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjA1NjksIm5iZiI6MTcwMTI2MDI2OSwicGF0aCI6Ii85NzA4ODQ5NC8yODY1NTk4ODUtNDQxMDYxNGYtYzRkMy00NDZjLWEzYzctNzUxMjg3NTJmODZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEyMTc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMjUxZTg3MjAwOTljNGViOWQ5NTQ2YjdmZGMzZjliNGU2NjM3OTVhNzYzNzE2ZGQ3N2E5OWE2Yjk1NWM2YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xrqvBuKKePBm54aWzucMoWcF0mlK8G7B287LQb_ru0Q)

Try to re-install FS via `pip install -e .`.

**Comment by tntstation** [comment]
I'm sorry for arbitrarily assuming it was an issue with the. yaml file before carefully checking. I didn't realize that the. yaml file format in the backdoor bench is different. I have other questions, but to help others who see this issue, I will create a new one. Thank you for your patience in answering.

**Comment by HansJack1999** [comment]
Hi, @tntstation 
Thank you very much for your question.  It helped me solve the issue with running the specified config.  However, as a beginner, I still have many questions I’d like to ask.  If possible, I’d love to connect privately for further discussion.  My email is 1047965818@qq.com, and I look forward to your response.
