### ISSUE TITLE
How to split the data to clients first then split to [train, validation, test] ?

### ISSUE THREAD

**Issue by SpeeeedLee** [alibaba/FederatedScope#724]
It seems to me that the provided code first split the data into three sets, [train, validation, test].
Then, these three sets are further divided to each client in different three times.

However, if I want to conduct a self-define non-iid partition, I will certainly want the partition be conducted only once, and each client gets similar data distribution on its training, validation, and test sets.

So, can anyone please give me any idea of how to first do the non-iid partition(to clients), then do the [train, validation, test] partition?

Or maybe I misunderstood the code?

Thank you!

**Comment by rayrayraykk** [comment]
As you can see in: https://federatedscope.io/docs/fs-data/, data are split via:
`Dataset -> ML split -> FL split -> FS Dataloader`

If you want to implement your split method (i.e., Dataset -> FL split -> ML split  -> FS Dataloader), you can use `DummyDataTranslator` in https://github.com/alibaba/FederatedScope/blob/llm/federatedscope/core/data/dummy_translator.py (just convert a data dict to our format), or modify it  as you wish.
