### ISSUE TITLE
Is there any way of evaluating clients' validation loss before FedAvg?

### ISSUE THREAD

**Issue by SpeeeedLee** [alibaba/FederatedScope#725]
As title, say I am performing FedPub.

Is there anyway I can calculate and record the clients' validation loss after it tain locally and before the model is sent back for aggregation.

Thank you.

**Comment by SpeeeedLee** [comment]
I already set 
eval.split = ['validation']
eval.metrics = ['acc']
, but the output is still like this :

![1701187597710](https://github.com/alibaba/FederatedScope/assets/132431571/fd881561-4b80-44ad-a46b-c4a253552d3b)

So is it correct that the code will only evaluate the metrics on train set no matter the  eval.split setting?
And eval.split setting is for the evaluation of the server side?

Please give me any correction, I am confused, thanks!

**Comment by rayrayraykk** [comment]
`eval.split = ['test', 'val']` should be right.

For more details about usage of config, please refer to https://github.com/alibaba/FederatedScope/blob/llm/federatedscope/core/configs/README.md
