### ISSUE TITLE
Some questions of evaluating LLama-7b with helm

### ISSUE THREAD

**Issue by zhentongLi** [alibaba/FederatedScope#731]
Hello! May I ask, when evaluating with helm, there are some parameters in one of the commands, and I don't know exactly what it does.
![image](https://github.com/alibaba/FederatedScope/assets/51142969/c62c7fb5-227e-4364-bfe2-abcbdc5c8479)
Could you explain the two steps in detail？Thank you！

**Comment by qbc2016** [comment]
Hello, we explained the meaning of each parameter above.
![F753D2ED-94D9-4A08-8136-73F54226EC00](https://github.com/alibaba/FederatedScope/assets/22984042/18b40405-1d54-459a-bb5b-a5420996cf9a)

**Comment by zhentongLi** [comment]
Currently I have fine-tuned the model with dolly-15k@llm data, the configuration file is llama_modelscope.yaml, and after that I want to evaluate it, and I see that there are some steps in the readme.md of this eval_for_helm package that aren't quite clear in the deployment process via Conda. For example, the package structure in the helm_fs package is not clear. And maybe there is a mistake in this readme.md. Could you give me the clear structure and another advice about the evaluation? Thank you very much!
![image](https://github.com/alibaba/FederatedScope/assets/51142969/026aaa47-3613-4c0f-8cd6-c8f414d24c1f)

**Comment by qbc2016** [comment]
Thank you for pointing it out, the second term should be `PATH_WORKDIR=~/helm_fs/src/crfm-helm` . 
There are two steps during the evaluation with helm.
The first step is to evaluate, i.e., run the code in `Start to evaluate` ; you may also add the path of your yaml file in the command as `--yaml xx/xx/llama_modelscope.yaml` . Note that you should change the relative path in`federate.save_to`  to absolute path.
The second step is to view the results, which is in`Launch webserver to view results` . 
 You can try it out and feel free to ask any questions.
