### ISSUE TITLE
some question about secret sharing

### ISSUE THREAD

**Issue by tntstation** [alibaba/FederatedScope#735]
would like to make some modifications to the secret sharing. Currently, it seems that secret sharing involves exchanging frames between all clients. However, I would like clients to be divided into multiple groups, and clients within each group can exchange frames with each other. Can you give me some suggestions?

**Comment by qbc2016** [comment]
Hello, we use an (n, n)-secret sharing scheme, that is, a secret value is partitioned into n pieces. The value can be recovered if and only if one holds all n pieces.  For example, if a client has a secret value $`s`$, he partitions it into $`[s_1, s_2, \ldots, s_n]`$, and sends $`s_i`$ to client$`_i`$. See [here](https://github.com/alibaba/FederatedScope/blob/480b67de851df2fa02b7cc2189f1803d947998d7/federatedscope/core/workers/client.py#L382).
In my opinion, if you want the clients to exchange their frames within a small group, it may be convenient to maintain a list containing the neighbors among the group, and then send it in a similar way.
I'm not sure if this has addressed your question.

**Comment by tntstation** [comment]
Thank you for your answer. I still have some questions about secret sharing.
![image](https://github.com/alibaba/FederatedScope/assets/97088494/2f072bf0-e241-474b-bd35-e2e025d26611)
In this section of the code in sever.py, the AdditiveSecretSharing class sets shared_party_num to int(self._cfg.federate.sample_client_num). However, use_ss is only set to true when all clients participate, so sample_client_num will be -1.
![image](https://github.com/alibaba/FederatedScope/assets/97088494/e5479b36-e513-4f75-ac99-7ba1b363e189)
I'm confused because in secret_sharing.py, shared_party_num is required to be greater than -1. I'm not sure where I'm misunderstanding.

**Comment by qbc2016** [comment]
"However, use_ss is only set to true when all clients participate, so sample_client_num will be -1." This is not true. When use ss, we assert that `cfg.federate.client_num == cfg.federate.sample_client_num` , see [here](https://github.com/alibaba/FederatedScope/blob/480b67de851df2fa02b7cc2189f1803d947998d7/federatedscope/core/configs/cfg_fl_setting.py#L188)

**Comment by tntstation** [comment]
thank you，it is really helpful for me
