### ISSUE TITLE
ConfigSpace Object has no attribute to .item()

### ISSUE THREAD

**Issue by SkyTu** [alibaba/FederatedScope#736]
**Describe the bug**
ConfigSpace Object has no attribute to .item()

**To Reproduce**
Ubuntu 18.04, python 3.9, configspace 0.4.19 
1. Go to 'FederatedScope/benchmark/FedHPOBench'
2. Run 'example.py'
3. See error

**Expected behavior**
1. Adjust the "_check" function in tabular_benchmark.py and surrogate_benchmark.py. Ensure that "configuration" and "fidelity" are dictionaries.
2. Specify the exact version of configspace.

**Screenshots**
<img width="316" alt="error" src="https://github.com/alibaba/FederatedScope/assets/51221273/0d9afcc5-d9b3-4e9f-90ee-13bd79d9f1b1">

**Comment by SkyTu** [comment]
<img width="619" alt="image" src="https://github.com/alibaba/FederatedScope/assets/51221273/e8a5fe56-f288-45af-b3d0-3c6f35abaf2b">

The problem can be solved this way, and the bug needs to be fixed.

**Comment by rayrayraykk** [comment]
It appears that the error is due to an incompatibility with your version of ConfigSpace. As indicated here: https://github.com/alibaba/FederatedScope/blob/480b67de851df2fa02b7cc2189f1803d947998d7/setup.py#L29, please try reinstalling with `pip install -e .[hpo]` and then try again. Thank you.

**Comment by SkyTu** [comment]
Thank you for your reply!
