### ISSUE TITLE
LDA splitter：ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by zhangtian-3841** [alibaba/FederatedScope#758]
您好！我按照官网文档添加mnist数据集后，在使用LDA进行数据划分时，出现以下错误。您可否帮我看看这个问题呢
load_mnist:
<img width="547" alt="屏幕截图 2024-03-06 150524" src="https://github.com/alibaba/FederatedScope/assets/82702815/54238261-4a08-4726-8e25-cc92e4e858b2">

配置文件中关于data的部分：
`data:
  root: data/
  type: mnist
  splits: [0.6,0.2,0.2]
  subsample: 0.05
  transform: [['ToTensor'], ['Normalize', {'mean': [0.9637], 'std': [0.1592]}]]
  splitter: lda
  splitter_args: [{'alpha': 0.1}]`

出现的错误：
<img width="530" alt="83bc3138cf2d903ad1b11a28d4a08fa" src="https://github.com/alibaba/FederatedScope/assets/82702815/8e928a7a-1ce4-49e2-af58-44c203fb771b">

**Comment by rayrayraykk** [comment]
The data format should be list of tuples, such as `[(x, y), (x, y), (x, y), ...]`.

**Comment by zhangtian-3841** [comment]
十分感谢您！
