### ISSUE TITLE
Will there be the vertical federated learning for the GAN network?

### ISSUE THREAD

**Issue by HeliumzzZ** [alibaba/FederatedScope#77]
Will there be the vertical federated learning for the GAN network?

**Comment by xieyxclack** [comment]
Thanks for your interest!

It is a good idea to apply the vertical federated learning to the GAN network, but we don't have a clear short-term plan for it by now. We really appreciate some contributions (e.g., implementation and/or related works) to FederatedScope that are related to this, and we will help out as much as we can.

**Comment by xieyxclack** [comment]
Hope that helps! This thread is closed and let us know if you have more questions.
