### ISSUE TITLE
关于配置环境

### ISSUE THREAD

**Issue by TonyStartXiong** [alibaba/FederatedScope#780]
在gfl的README文件里说“conda install -y rdkit=2021.09.4=py39hccf6a74_0 -c conda-forge”
可是网上找不到rdkit2021.09.4的版本

**Comment by czzhangheng** [comment]
不用太纠结版本问题，我随便 `pip install rdkit` 就跑起来了
pip list 显示的版本是`rdkit                   2024.3.5`
此外，我跑脚本时还需要额外安装两个包，除此之外，按照根目录中的readme中安装即可
`pip install python-louvain`
`pip install community`
希望对你有帮助
