### ISSUE TITLE
我在国内 从你们那边跑例子 下数据下不下来怎么解决

### ISSUE THREAD

**Issue by HeliumzzZ** [alibaba/FederatedScope#80]

**Comment by HeliumzzZ** [comment]
return opener.open(url, data, timeout)
  File "F:\Anaconda3\envs\Federated\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "F:\Anaconda3\envs\Federated\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "F:\Anaconda3\envs\Federated\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "F:\Anaconda3\envs\Federated\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "F:\Anaconda3\envs\Federated\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>

**Comment by xieyxclack** [comment]
Thanks for your interest :) I have assigned this thread to @rayrayraykk

**Comment by rayrayraykk** [comment]
Please provide the detailed command or config you used, thanks.

**Comment by HeliumzzZ** [comment]
> Please provide the detailed command or config you used, tha
conda install --file enviroment/requirements-torch1.10.txt -c pytorch -c conda-forge -c nvidia

use code in quickstart in my computer not jupyterlab 
https://try.federatedscope.io/user/heliumzzz/lab/tree/01_quick_start.ipynb

**Comment by HeliumzzZ** [comment]
> Please provide the detailed command or config you used, thanks.

from federatedscope.core.auxiliaries.data_builder import get_data

cfg.data.type = 'femnist'
cfg.data.splits = [0.6, 0.2, 0.2]
cfg.data.batch_size = 10
cfg.data.subsample = 0.05
cfg.data.transform = [['ToTensor'], ['Normalize', {'mean': [0.1307], 'std': [0.3081]}]]

data, modified_cfg = get_data(cfg.clone())
cfg.merge_from_other_cfg(modified_cfg)

**Comment by HeliumzzZ** [comment]
> Please provide the detailed command or config you used, thanks.

error in get_data

**Comment by rayrayraykk** [comment]
Can you download the data file from

**Comment by HeliumzzZ** [comment]
> Can you download the data file from https://federatedscope.oss-cn-beijing.aliyuncs.com/femnist_all_data.zip

i can

**Comment by HeliumzzZ** [comment]
> Can you download the data file from https://federatedscope.oss-cn-beijing.aliyuncs.com/femnist_all_data.zip

下一步我应该如何处理数据 和getdata返回值里一样

**Comment by rayrayraykk** [comment]
> > Can you download the data file from https://federatedscope.oss-cn-beijing.aliyuncs.com/femnist_all_data.zip
> 
> 下一步我应该如何处理数据 和getdata返回值里一样

Here are two possible solutions:
1. Update your `urllib` and `ssl` packages in your python env.
2. As the `cfg.data.root='data'`, you can move `femnist_all_data.zip` to `data/femnist/raw` and try again.

Hope this will help.

**Comment by HeliumzzZ** [comment]
> > > Can you download the data file from https://federatedscope.oss-cn-beijing.aliyuncs.com/femnist_all_data.zip
> > 
> > 
> > 下一步我应该如何处理数据 和getdata返回值里一样
> 
> Here are two possible solutions:
> 
> 1. Update your `urllib` and `ssl` packages in your python env.
> 2. As the `cfg.data.root='data'`, you can move `femnist_all_data.zip` to `data/femnist/raw` and try again.
> 
> Hope this will help.

urllib3                 1.26.9

**Comment by HeliumzzZ** [comment]
我将数据放到了data下的 raw目录
from federatedscope.core.auxiliaries.data_builder import get_data

cfg.data.root = 'data'
cfg.data.splits = [0.6, 0.2, 0.2]
cfg.data.batch_size = 10
cfg.data.subsample = 0.05
cfg.data.transform = [['ToTensor'], ['Normalize', {'mean': [0.1307], 'std': [0.3081]}]]

data, modified_cfg = get_data(cfg.clone())

cfg.merge_from_other_cfg(modified_cfg)
这是我的代码 

Traceback (most recent call last):
  File "F:\Federated\trainer.py", line 47, in <module>
    Fed_runner = FedRunner(data=data,
  File "F:\Anaconda3\envs\Federated\lib\site-packages\federatedscope-0.1.0-py3.9.egg\federatedscope\core\fed_runner.py", line 38, in __init__
    self._setup_for_standalone()
  File "F:\Anaconda3\envs\Federated\lib\site-packages\federatedscope-0.1.0-py3.9.egg\federatedscope\core\fed_runner.py", line 50, in _setup_for_standalone
    self.server = self._setup_server()
  File "F:\Anaconda3\envs\Federated\lib\site-packages\federatedscope-0.1.0-py3.9.egg\federatedscope\core\fed_runner.py", line 158, in _setup_server
    model = get_model(self.cfg.model,
  File "F:\Anaconda3\envs\Federated\lib\site-packages\federatedscope-0.1.0-py3.9.egg\federatedscope\core\auxiliaries\model_builder.py", line 54, in get_model
    model = get_cnn(model_config, local_data)
  File "F:\Anaconda3\envs\Federated\lib\site-packages\federatedscope-0.1.0-py3.9.egg\federatedscope\cv\model\model_builder.py", line 14, in get_cnn
    data = next(iter(local_data['train']))
TypeError: 'NoneType' object is not iterable

Process finished with exit code 1

**Comment by HeliumzzZ** [comment]
> > > Can you download the data file from https://federatedscope.oss-cn-beijing.aliyuncs.com/femnist_all_data.zip
> > 
> > 
> > 下一步我应该如何处理数据 和getdata返回值里一样
> 
> Here are two possible solutions:
> 
> 1. Update your `urllib` and `ssl` packages in your python env.
> 2. As the `cfg.data.root='data'`, you can move `femnist_all_data.zip` to `data/femnist/raw` and try again.
> 
> Hope this will help.

我的urllib3版本是1.26.9

**Comment by rayrayraykk** [comment]
> 

Make sure the `data` directory contains:
```
-data
--femnist
---raw
----femnist_all_data.zip
```

If your `data` directory contains `processed`:
```
-data
--femnist
---raw
----all_data
----femnist_all_data.zip
---processed
----xxxxxxx
```
Please delete `processed` and try again.

**Comment by HeliumzzZ** [comment]
![image](https://user-images.githubusercontent.com/96455578/167789288-51e100e4-fc1a-4108-a283-7a402f242a18.png)

**Comment by HeliumzzZ** [comment]
> > 
> 
> Make sure the `data` directory contains:
> 
> ```
> -data
> --femnist
> ---raw
> ----femnist_all_data.zip
> ```
> 
> If your `data` directory contains `processed`:
> 
> ```
> -data
> --femnist
> ---raw
> ----all_data
> ----femnist_all_data.zip
> ---processed
> ----xxxxxxx
> ```
> 
> Please delete `processed` and try again.

但是还是报同样的错误

**Comment by rayrayraykk** [comment]
> > > 
> > 
> > 
> > Make sure the `data` directory contains:
> > ```
> > -data
> > --femnist
> > ---raw
> > ----femnist_all_data.zip
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If your `data` directory contains `processed`:
> > ```
> > -data
> > --femnist
> > ---raw
> > ----all_data
> > ----femnist_all_data.zip
> > ---processed
> > ----xxxxxxx
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please delete `processed` and try again.
> 
> 但是还是报同样的错误

Please join our DingDing group for your case, thanks. The QR code can be found in:
https://federatedscope.io/docs/community/

**Comment by HeliumzzZ** [comment]
谢谢您的耐心解答 真心感谢

**Comment by rayrayraykk** [comment]
Welcome :>

**Comment by HeliumzzZ** [comment]
> Welcome :>

我已经提交了DingDing申请 这边示例代码也运行成功了 真心感谢
