### ISSUE TITLE
A problem when using Adam optimizer

### ISSUE THREAD

**Issue by wanghh7** [alibaba/FederatedScope#91]
https://github.com/alibaba/FederatedScope/blob/28d325bcb65d904db1b70a22c90441bdbeed654c/federatedscope/core/auxiliaries/optimizer_builder.py#L14

https://github.com/alibaba/FederatedScope/blob/28d325bcb65d904db1b70a22c90441bdbeed654c/federatedscope/core/trainers/context.py#L108

Adam got an unexpected keyword argument 'momentum'.

**Comment by xieyxclack** [comment]
Thanks for pointing out the issue. I have assigned this thread to @DavdGao
