### ISSUE TITLE
Is there some complete tutorial about how to put into myself data/model/trainer and run a FL task?

### ISSUE THREAD

**Issue by lmaxeniro** [alibaba/FederatedScope#93]
Hi, I am trying to follow up on the guidance here: https://federatedscope.io/docs/own-case/, to add the data/model/trainer etc.,  into the project and run up an FL task.
However, this guidance is not that clear, particularly, 1). what does the config section work; 2). how to unify the customized data/model/trainer/config together to complete an FL task.
Is that possible to have complete guidance by using something like mnist/cifar10?

**Comment by rayrayraykk** [comment]
Thanks for your attention!
You can try our [playground](try.federatedscope.io), where you will get hands-on guidance with MNIST.
